# This is a basic workflow to help you get started with Actions

name: auto release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true


      - name: Get repository and package name
        id: vars
        run: |
            echo ::set-output name=repository::${GITHUB_REPOSITORY#*/}
            echo ::set-output name=package::${GITHUB_REPOSITORY#*/}-${GITHUB_REF/refs\/tags\//}

      - name: Generate deployment zip package
        run: cd ${RUNNER_WORKSPACE} && zip -r ${{ steps.vars.outputs.package }}.zip ${{ steps.vars.outputs.repository }}  -x '*.git*'

      - name: Generate deployment tgz package
        run: cd ${RUNNER_WORKSPACE} && tar -zcvf ${{ steps.vars.outputs.package }}.tar.gz --exclude=${{ steps.vars.outputs.repository }}/.github --exclude=${{ steps.vars.outputs.repository }}/.git  ${{ steps.vars.outputs.repository }}

      - name: Move package
        run: |
          mv ${RUNNER_WORKSPACE}/${{ steps.vars.outputs.package }}.zip ${GITHUB_WORKSPACE}
          mv ${RUNNER_WORKSPACE}/${{ steps.vars.outputs.package }}.tar.gz ${GITHUB_WORKSPACE}
          
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.vars.outputs.package }}.zip
            ${{ steps.vars.outputs.package }}.tar.gz 

